# Generated by Django 6.0 on 2025-12-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_board_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
